apiVersion: v1
kind: Service
metadata:
  name: {{ include "controlr.fullname" . }}
  labels:
    {{- include "controlr.labels" . | nindent 4 }}
  {{- with .Values.controlr.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.controlr.service.type }}
  ports:
  - port: {{ .Values.controlr.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "controlr.selectorLabels" . | nindent 4 }}
