{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "controlr.postgresql.fullname" . }}
  labels:
    {{- include "controlr.postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
  - port: {{ .Values.postgresql.service.port }}
    targetPort: postgresql
    protocol: TCP
    name: postgresql
  selector:
    {{- include "controlr.postgresql.selectorLabels" . | nindent 4 }}
{{- end }}
