{{- if and .Values.postgresql.enabled .Values.postgresql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "controlr.postgresql.fullname" . }}
  labels:
    {{- include "controlr.postgresql.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.postgresql.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size | quote }}
  {{- if .Values.postgresql.persistence.storageClass }}
  {{- if (eq "-" .Values.postgresql.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
